# Generated by Django 3.2.3 on 2021-05-25 23:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_auto_20210525_0056'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='spoiler',
            new_name='spoilers',
        ),
    ]
